// src/Modules/Trait/TraitType.ts
export enum TraitType {
  AppSelector = 'action.devices.traits.AppSelector',
  ArmDisarm = 'action.devices.traits.ArmDisarm',
  Brightness = 'action.devices.traits.Brightness',
  CameraStream = 'action.devices.traits.CameraStream',
  ColorSetting = 'action.devices.traits.ColorSetting',
  Cook = 'action.devices.traits.Cook',
  Dispense = 'action.devices.traits.Dispense',
  Dock = 'action.devices.traits.Dock',
  EnergyStorage = 'action.devices.traits.EnergyStorage',
  FanSpeed = 'action.devices.traits.FanSpeed',
  Fill = 'action.devices.traits.Fill',
  HumiditySetting = 'action.devices.traits.HumiditySetting',
  InputSelector = 'action.devices.traits.InputSelector',
  LightEffects = 'action.devices.traits.LightEffects',
  Locator = 'action.devices.traits.Locator',
  LockUnlock = 'action.devices.traits.LockUnlock',
  MediaState = 'action.devices.traits.MediaState',
  Modes = 'action.devices.traits.Modes',
  NetworkControl = 'action.devices.traits.NetworkControl',
  OnOff = 'action.devices.traits.OnOff',
  OpenClose = 'action.devices.traits.OpenClose',
  Reboot = 'action.devices.traits.Reboot',
  Rotation = 'action.devices.traits.Rotation',
  RunCycle = 'action.devices.traits.RunCycle',
  Scene = 'action.devices.traits.Scene',
  SensorState = 'action.devices.traits.SensorState',
  SoftwareUpdate = 'action.devices.traits.SoftwareUpdate',
  StartStop = 'action.devices.traits.StartStop',
  StatusReport = 'action.devices.traits.StatusReport',
  TemperatureControl = 'action.devices.traits.TemperatureControl',
  TemperatureSetting = 'action.devices.traits.TemperatureSetting',
  Timer = 'action.devices.traits.Timer',
  Toggles = 'action.devices.traits.Toggles',
  TransportControl = 'action.devices.traits.TransportControl',
  Volume = 'action.devices.traits.Volume',
}
